-- =============================================================================
-- SentinelAML Copilot — load synthetic seed data into RAW.*
-- Spec: aml-regulatory-copilot | Task 5.1 | Requirements: 2.1, 2.2, 2.3
-- Generated by snowflake/seed/generate_seed.py — DO NOT EDIT BY HAND.
-- =============================================================================
-- All data here is fully synthetic (Req 2.1). Run AFTER the RAW DDL
-- (snowflake/ddl/01_raw.sql). Files are loaded from an internal stage; adjust
-- the PUT paths to the directory containing the generated CSVs.
--
--   snow sql -c governed-aml -D db=GOVERNED_AML -f snowflake/seed/data/load.sql
-- =============================================================================

SET db = 'GOVERNED_AML';
USE DATABASE IDENTIFIER($db);
USE SCHEMA RAW;

CREATE FILE FORMAT IF NOT EXISTS RAW.SEED_CSV_FORMAT
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('', 'NULL')
    EMPTY_FIELD_AS_NULL = TRUE
    TIMESTAMP_FORMAT = 'YYYY-MM-DD"T"HH24:MI:SS';

CREATE STAGE IF NOT EXISTS RAW.SEED_STAGE
    FILE_FORMAT = RAW.SEED_CSV_FORMAT
    COMMENT = 'Internal stage for synthetic seed CSVs (Req 2.1).';

-- Upload the generated CSVs (run from the directory holding this load.sql).
PUT 'file://entity.csv'            @RAW.SEED_STAGE OVERWRITE = TRUE AUTO_COMPRESS = FALSE;
PUT 'file://transaction_event.csv' @RAW.SEED_STAGE OVERWRITE = TRUE AUTO_COMPRESS = FALSE;
PUT 'file://alert.csv'             @RAW.SEED_STAGE OVERWRITE = TRUE AUTO_COMPRESS = FALSE;
PUT 'file://policy_doc.csv'        @RAW.SEED_STAGE OVERWRITE = TRUE AUTO_COMPRESS = FALSE;

COPY INTO RAW.ENTITY (entity_id, display_name_masked, attributes)
    FROM (
        SELECT $1, $2, TRY_PARSE_JSON($3)
        FROM @RAW.SEED_STAGE/entity.csv
    )
    FILE_FORMAT = (FORMAT_NAME = RAW.SEED_CSV_FORMAT)
    ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.TRANSACTION_EVENT
    (event_id, entity_id, amount, currency, occurred_at, ingested_at, source, is_duplicate_suppressed)
    FROM @RAW.SEED_STAGE/transaction_event.csv
    FILE_FORMAT = (FORMAT_NAME = RAW.SEED_CSV_FORMAT)
    ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.ALERT (alert_id, entity_id, typology, raised_at, correlation_key)
    FROM @RAW.SEED_STAGE/alert.csv
    FILE_FORMAT = (FORMAT_NAME = RAW.SEED_CSV_FORMAT)
    ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.POLICY_DOC (policy_doc_id, title, body, source, version, ingested_at)
    FROM @RAW.SEED_STAGE/policy_doc.csv
    FILE_FORMAT = (FORMAT_NAME = RAW.SEED_CSV_FORMAT)
    ON_ERROR = 'ABORT_STATEMENT';
