"""SAR Drafting Service (interface + ``Impl``).

This service drafts an audit-ready Suspicious Activity Report (SAR) for a case
while preserving the one separation that makes the copilot audit-ready rather
than a generic chatbot (design §6; Req 6). A SAR draft is decision support, not
a filing — the LLM narrates around governed numbers, it never produces them, and
nothing is ever auto-filed.

:meth:`SARService.draft` assembles four parts, each mapped to a correctness
property:

* **Entity summary + suspicious pattern (Req 6.1).** Both narrative sections are
  generated by Cortex ``COMPLETE`` from the governed figures and the cited policy
  passages only. The LLM is handed numbers + passages and asked to narrate; it
  never invents a figure (Req 3.2).
* **Governed figures (Req 6.2, Property 22).** The entity's governed risk is read
  through the :class:`MetricService` (the sole figure source). Each
  :class:`~app.models.governed.GovernedMetricValue` already carries its
  ``metric_definition_version`` and :class:`~app.models.common.QueryLineage`, so
  every figure is linked to metric + version + lineage.
* **Cited policy basis (Req 6.2).** Policy passages are retrieved through the
  guarded :class:`CortexAdapter` (every chunk injection-scanned before it can feed
  a model call, Req 9.1) and surfaced as policy-passage
  :class:`~app.models.common.EvidenceItem` citations, so every regulatory
  assertion traces to a cited passage.
* **Grounding / completeness (Req 6.3, Property 23).** A draft is structurally
  complete *iff* it has a non-empty entity summary, a non-empty suspicious
  pattern, at least one governed figure, and at least one policy citation
  (Property 21). If any required element cannot be grounded — no governed figure,
  no policy citation, or (fail-safe) Cortex unavailable so no narrative — the
  draft is marked ``incomplete``, ``ungrounded_elements`` lists exactly those
  elements, and it is **not** filing-ready.

Two hard labels always hold (Req 6.4, Property 24): the draft is
``is_ai_generated_decision_support`` (always true), and it is **never auto-filed**
— this service has no filing/transmit path at all; a SAR status never becomes
``filed`` here (filing is simulated only after human approval, Req 6.5).

If Cortex is unavailable (:class:`CortexUnavailableError`) the service **fails
safe** (Req 13.1): it still returns a :class:`SARDraft`, but one that is
``incomplete`` with the narrative elements listed as ungrounded and never
presented as filing-ready — it never fabricates a narrative.

All collaborators (:class:`MetricService`, :class:`CortexAdapter`,
:class:`AuditService`) are injected with safe in-memory/default fallbacks (except
the Cortex adapter, which requires a session), so the service is unit-testable
with fakes — consistent with the investigation/grounding services.
"""

from __future__ import annotations

from typing import Optional, Protocol, runtime_checkable

from app.models.answer import SARDraft
from app.models.case import Case
from app.models.common import EvidenceItem
from app.models.governed import GovernedMetricValue
from app.services.audit_service import (
    SYSTEM_ACTOR,
    AuditService,
    AuditServiceImpl,
    build_audit_record,
)
from app.services.metric_service import MetricService, MetricServiceImpl
from app.snowflake.cortex import CortexAdapter, CortexUnavailableError

# ---------------------------------------------------------------------------
# Canonical audit action names (stable + package-private so the audit trail is
# queryable and the SAR property tests can assert the recorded operations).
# ---------------------------------------------------------------------------

# Recorded when a complete, filing-ready-structured SAR draft is produced.
ACTION_SAR_DRAFTED = "sar.drafted"

# Recorded when a SAR draft is produced but incomplete (some element ungrounded),
# including the Cortex-unavailable fail-safe path (Req 6.3, Req 13.1).
ACTION_SAR_INCOMPLETE = "sar.incomplete"

# ---------------------------------------------------------------------------
# Stable identifiers for the required SAR elements. Listed verbatim in
# ``ungrounded_elements`` so a reviewer sees exactly which element could not be
# grounded (Req 6.3, Property 23).
# ---------------------------------------------------------------------------

ELEMENT_ENTITY_SUMMARY = "entity_summary"
ELEMENT_SUSPICIOUS_PATTERN = "suspicious_pattern"
ELEMENT_GOVERNED_FIGURES = "governed_figures"
ELEMENT_POLICY_CITATIONS = "policy_citations"


@runtime_checkable
class SARService(Protocol):
    """Draft an audit-ready SAR for a case (design §6; Req 6)."""

    def draft(self, case: Case) -> SARDraft:
        """Produce a :class:`SARDraft` for ``case``.

        The draft contains an entity summary, the suspicious pattern, the governed
        risk figures (each linked to metric + version + lineage, Req 6.2), and the
        cited policy basis. It is structurally complete iff it has a non-empty
        summary and pattern, at least one governed figure, and at least one policy
        citation (Property 21); otherwise it is ``incomplete`` with
        ``ungrounded_elements`` listing exactly the ungrounded elements and is not
        filing-ready (Req 6.3, Property 23). The draft is always labelled
        AI-generated decision support and is never auto-filed (Req 6.4,
        Property 24); Cortex unavailability fails safe with an incomplete draft and
        no fabricated narrative (Req 13.1).
        """
        ...


class SARServiceImpl:
    """Default :class:`SARService` wiring the governed collaborators.

    Figures come from the :class:`MetricService` (the only figure source); the
    policy basis and the two narrative sections come from the guarded
    :class:`CortexAdapter`; every draft is audited through the
    :class:`AuditService`. A :class:`CortexAdapter` must be supplied (it requires a
    session); the remaining collaborators default to in-memory/default
    implementations for local runs and unit tests.
    """

    def __init__(
        self,
        cortex: CortexAdapter,
        *,
        metric_service: Optional[MetricService] = None,
        audit_service: Optional[AuditService] = None,
    ) -> None:
        self._cortex = cortex
        self._metrics: MetricService = (
            metric_service if metric_service is not None else MetricServiceImpl()
        )
        self._audit: AuditService = (
            audit_service if audit_service is not None else AuditServiceImpl()
        )

    # ------------------------------------------------------------------
    # draft
    # ------------------------------------------------------------------

    def draft(self, case: Case) -> SARDraft:
        """See :meth:`SARService.draft`."""
        # 1. Governed figures: the ONLY source of regulatory figures (Req 3.2,
        #    Req 6.2). Read through the metric service; each value already carries
        #    its metric_definition_version + query lineage, so every figure is
        #    linked to metric + version + lineage (Property 22).
        governed_figures = self._governed_figures(case)

        # 2. Cited policy basis: guarded policy passages (each injection-scanned by
        #    the Cortex adapter before it could feed any model call, Req 9.1).
        #    Fail safe if Cortex is unavailable — never fabricate a citation.
        cortex_available = True
        policy_citations: list[EvidenceItem] = []
        try:
            policy_citations = self._policy_citations(case)
        except CortexUnavailableError:
            cortex_available = False

        # 3. Narrative sections: generated by Cortex from the governed figures +
        #    cited passages only (Req 6.1). On Cortex unavailability (or if it was
        #    already down for retrieval) we fail safe with empty narrative and let
        #    the grounding step mark those elements ungrounded (Req 13.1) — never a
        #    fabricated narrative.
        entity_summary = ""
        suspicious_pattern = ""
        if cortex_available:
            try:
                entity_summary = self._generate_entity_summary(
                    case, governed_figures, policy_citations
                )
                suspicious_pattern = self._generate_suspicious_pattern(
                    case, governed_figures, policy_citations
                )
            except CortexUnavailableError:
                cortex_available = False
                entity_summary = ""
                suspicious_pattern = ""

        # 4. Grounding / completeness: collect exactly the required elements that
        #    could not be grounded (Req 6.3, Property 23). A draft is structurally
        #    complete iff all four required elements are present (Property 21).
        ungrounded_elements = _ungrounded_elements(
            entity_summary, suspicious_pattern, governed_figures, policy_citations
        )
        completeness = "complete" if not ungrounded_elements else "incomplete"

        draft = SARDraft(
            case_id=case.case_id,
            entity_summary=entity_summary,
            suspicious_pattern=suspicious_pattern,
            governed_figures=governed_figures,
            policy_citations=policy_citations,
            completeness=completeness,
            ungrounded_elements=ungrounded_elements,
            # Always decision support; never auto-filed (Req 6.4, Property 24).
            is_ai_generated_decision_support=True,
        )

        # 5. Audit the produced draft with its completeness outcome (Req 8.1). The
        #    governed metric version is stamped where a figure is involved (Req 8.2).
        self._audit.append(
            build_audit_record(
                action=ACTION_SAR_DRAFTED if completeness == "complete" else ACTION_SAR_INCOMPLETE,
                actor_id=SYSTEM_ACTOR,
                case_ref=case.case_id,
                entity_ref=case.entity_id,
                input_refs=[case.case_id],
                output_refs=[completeness, *ungrounded_elements],
                metric_definition_version=_first_version(governed_figures),
            )
        )
        return draft

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _governed_figures(self, case: Case) -> list[GovernedMetricValue]:
        """Return the governed figures backing the SAR, read governed-only (Req 6.2).

        Reuses the governed risk aggregation already computed for the case (itself
        populated solely from :class:`GovernedMetricValue` instances read from the
        semantic view). Falls back to re-aggregating via the metric service when
        the case carries no metrics, so the SAR always reflects the governed
        snapshot and never a value from narrative (Req 3.2, Property 6).
        """
        metrics = list(case.risk_aggregation.metrics)
        if metrics:
            return metrics
        return list(self._metrics.aggregate_entity_risk(case.entity_id).metrics)

    def _policy_citations(self, case: Case) -> list[EvidenceItem]:
        """Retrieve the guarded cited policy basis for the SAR (Req 6.2, Req 9.1).

        Delegates to the Cortex adapter, which embeds the query, ranks policy
        chunks, and routes every chunk through the Guard injection scan before
        returning it — so only clean passages reach this layer. Each clean chunk
        becomes a policy-passage :class:`EvidenceItem`, so every regulatory
        assertion in the draft can trace to a cited passage.
        """
        retrieval = self._cortex.retrieve_policy_evidence(
            _policy_query(case), case_ref=case.case_id, entity_ref=case.entity_id
        )
        return [
            EvidenceItem(
                kind="policy_passage",
                ref=chunk.source_ref or chunk.chunk_id,
                excerpt=chunk.chunk_text,
                lineage=None,
            )
            for chunk in retrieval.chunks
        ]

    def _generate_entity_summary(
        self,
        case: Case,
        governed_figures: list[GovernedMetricValue],
        policy_citations: list[EvidenceItem],
    ) -> str:
        """Generate the entity-summary narrative via Cortex ``COMPLETE`` (Req 6.1).

        The prompt is assembled from the governed figures and the already-scanned
        policy passages; the LLM narrates around the governed numbers and never
        invents one (Req 3.2). Any Cortex failure propagates as
        :class:`CortexUnavailableError`, which the caller turns into a fail-safe
        incomplete draft (Req 13.1).
        """
        prompt = _entity_summary_prompt(case, governed_figures, policy_citations)
        return self._cortex.complete(prompt).strip()

    def _generate_suspicious_pattern(
        self,
        case: Case,
        governed_figures: list[GovernedMetricValue],
        policy_citations: list[EvidenceItem],
    ) -> str:
        """Generate the suspicious-pattern narrative via Cortex ``COMPLETE`` (Req 6.1).

        Same governed-only prompting as :meth:`_generate_entity_summary`: the LLM
        describes the suspicious pattern using the governed figures + cited
        passages, never fabricating a figure (Req 3.2).
        """
        prompt = _suspicious_pattern_prompt(case, governed_figures, policy_citations)
        return self._cortex.complete(prompt).strip()


# ---------------------------------------------------------------------------
# Pure helpers (deterministic; no I/O).
# ---------------------------------------------------------------------------


def _ungrounded_elements(
    entity_summary: str,
    suspicious_pattern: str,
    governed_figures: list[GovernedMetricValue],
    policy_citations: list[EvidenceItem],
) -> list[str]:
    """List exactly the required SAR elements that could not be grounded (Req 6.3).

    The four required elements are the entity summary, the suspicious pattern, at
    least one governed figure, and at least one policy citation (Property 21). An
    element is ungrounded when its content is absent: an empty/blank narrative
    section, no governed figure, or no policy citation. The returned list contains
    exactly those elements, in a stable order, so ``completeness='incomplete'``
    and the draft is not filing-ready whenever it is non-empty (Property 23).
    """
    ungrounded: list[str] = []
    if not entity_summary or not entity_summary.strip():
        ungrounded.append(ELEMENT_ENTITY_SUMMARY)
    if not suspicious_pattern or not suspicious_pattern.strip():
        ungrounded.append(ELEMENT_SUSPICIOUS_PATTERN)
    if not governed_figures:
        ungrounded.append(ELEMENT_GOVERNED_FIGURES)
    if not policy_citations:
        ungrounded.append(ELEMENT_POLICY_CITATIONS)
    return ungrounded


def _first_version(governed_figures: list[GovernedMetricValue]) -> str | None:
    """The metric-definition version to stamp on the draft's audit record (Req 8.2)."""
    for figure in governed_figures:
        if figure.metric_definition_version:
            return figure.metric_definition_version
    return None


def _policy_query(case: Case) -> str:
    """Build the retrieval query for the SAR's cited policy basis (Req 6.2).

    A deterministic, governed query string over the case's entity and the
    governed metrics in its risk picture, so the retrieval is reproducible and
    carries no secret (Req 1.1).
    """
    metric_names = ", ".join(
        sorted({m.metric_name for m in case.risk_aggregation.metrics})
    ) or "entity risk"
    return (
        "Suspicious activity report policy basis for AML investigation of entity "
        f"{case.entity_id} covering governed risk metrics: {metric_names}."
    )


def _entity_summary_prompt(
    case: Case,
    governed_figures: list[GovernedMetricValue],
    policy_citations: list[EvidenceItem],
) -> str:
    """Assemble the Cortex prompt for the entity summary (governed-only; Req 3.2)."""
    return (
        "You are an AML compliance assistant drafting the ENTITY SUMMARY section "
        "of a Suspicious Activity Report. Summarise the entity under review using "
        "ONLY the governed figures and cited policy passages below. Do not invent, "
        "compute, or alter any number.\n\n"
        f"Entity under investigation: {case.entity_id}\n\n"
        f"Governed figures:\n{_figure_lines(governed_figures)}\n\n"
        f"Policy/evidence passages:\n{_citation_lines(policy_citations)}\n"
    )


def _suspicious_pattern_prompt(
    case: Case,
    governed_figures: list[GovernedMetricValue],
    policy_citations: list[EvidenceItem],
) -> str:
    """Assemble the Cortex prompt for the suspicious pattern (governed-only; Req 3.2)."""
    return (
        "You are an AML compliance assistant drafting the SUSPICIOUS PATTERN "
        "section of a Suspicious Activity Report. Describe the suspicious pattern "
        "for this entity using ONLY the governed figures and cited policy passages "
        "below. Do not invent, compute, or alter any number.\n\n"
        f"Entity under investigation: {case.entity_id}\n\n"
        f"Governed figures:\n{_figure_lines(governed_figures)}\n\n"
        f"Policy/evidence passages:\n{_citation_lines(policy_citations)}\n"
    )


def _figure_lines(governed_figures: list[GovernedMetricValue]) -> str:
    """Render governed figures (name = value, version) for a prompt."""
    return "\n".join(
        f"- {fig.metric_name} = {fig.value} (version {fig.metric_definition_version})"
        for fig in governed_figures
    ) or "- (no governed figures)"


def _citation_lines(policy_citations: list[EvidenceItem]) -> str:
    """Render cited policy passages ([ref] excerpt) for a prompt."""
    return "\n".join(
        f"- [{item.ref}] {item.excerpt}" for item in policy_citations if item.excerpt
    ) or "- (no supporting passages)"


__all__ = [
    "SARService",
    "SARServiceImpl",
    "ACTION_SAR_DRAFTED",
    "ACTION_SAR_INCOMPLETE",
    "ELEMENT_ENTITY_SUMMARY",
    "ELEMENT_SUSPICIOUS_PATTERN",
    "ELEMENT_GOVERNED_FIGURES",
    "ELEMENT_POLICY_CITATIONS",
]
